# Generated by Django 5.0.2 on 2024-03-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dietetica', '0002_alter_clientes_dni_alter_vendedores_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='DNI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='DNI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='direccion',
            field=models.CharField(max_length=40),
        ),
    ]
